### PR TITLE
Add changelog from PRs to readme.txt

### PR DESCRIPTION
**Pull request by opr**
# Description
This PR adds the changelog generated as part of the release process into the readme.txt file automatically.

To do this, I have:
- Opened the `readme.txt` file using the GitHub API and converted it from `base64` to `utf-8`.
- Replaced the `== Changelog ==` header with the same header plus the new changelog entry (generated here: https://github.com/woocommerce/automations/blob/5aa3cc7acf304c8f6a240bd2c111eb12a7f1c0b4/lib/utils/changelog/common/changelog.js#L407)
- Converted the new contents of the `readme.txt` file from `utf-8` back to `base64` (required format to update files via the REST api)
- Updated the `readme.txt` file using the GitHub REST API.

# Testing
To test this, you will need to:
- **Fork** the `woocommerce-gutenberg-products-block` and then unfork it (Go to this url: https://support.github.com/contact?tags=rr-forks and type `unfork` into the subject line. Follow the steps from the virtual assistant and wait 5-10 mins for the request to be actioned).
- Enable issues on your new unforked repository (go to `Settings > General > Features > Issues`)
- Activate GH actions
- Give read and write permissions to the workflows: Settings > Actions > General > Workflow permissions
- Allow GH actions to create PRs: Settings > Actions > General
- Create a milestone (I used 9.9.0, but pick whatever you like)
- Clone your repository locally.
- Create a PR on your repository, in this PR you should change the following file: https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/.github/workflows/release-pull-request.yml#L27
- Change the highlighted line to read: `uses: opr/automations@add/changelog-entry-to-readme`
- Merge the PR
- Optionally create multiple PRs.
- Assign them all to the milestone you created earlier.
- Create a new branch, `release/9.9.0` or whatever milestone number you picked.
- Push this branch to the remote.
- Go to your repository on GitHub, you should see a new PR created for the release, and it should have added the changelog to `readme.txt` 🙌🏼

### CODE REVIEW

**Comment by tarhi-saad** [comment]
For anyone else who wants to test this PR, don't forget to:

- Activate GH actions
- Give read and write permissions to the workflows: `Settings > Actions > General > Workflow permissions`
- Allow GH actions to create PRs: `Settings > Actions > General`

This is a great PR. Thank you, @opr!

I successfully tested the PR, and this is the result:

image

Is it possible to add the release version and the date above the added changelog?

**Comment by opr** [comment]
Hey Saad, thanks! I'll update the PR body now, I've also changed it to include the date and version number 🤦🏼

**Review by tarhi-saad — APPROVED** [review]
@opr, I've got the desired results by following the instructions above:

image

So, the PR is behaving as expected. Feel free to wait for other reviews if you want to have more eyes on this.

After merging the PR, you can remove the followings instructions from the release/patch checklists:

image

**Comment by alexflorisca** [comment]
@opr Do you want another pair of eyes on this or you happy with @tarhi-saad review?

**Comment by opr** [comment]
@alexflorisca yes please one more pair of eyes would be fab, thanks!

**Review by alexflorisca — APPROVED** [review]
👍  Nice, works like a charm. One thing though, can we store the action in the same repo? Seems to live in your personal Github atm?

**Comment by opr** [comment]
Actually, there's no need to change anything in Blocks, since this PR will be merged into `woocommerce/automations`, and `trunk` of Blocks uses `woocommerce/automations@v1` (which this PR will become part of after we release it).

Thanks @alexflorisca 👍🏼

**Comment by ralucaStan** [comment]
Nice work @opr 👏 
Would you mind also updating our release steps with this information. Maybe replace the current step with a note for the RM to check that the readme.txt was correctly updated? What do you think?

CC @Aljullu

**Comment by opr** [comment]
@ralucaStan done in https://github.com/woocommerce/woocommerce-blocks/pull/6422

**Pull request merged**
