### PR TITLE
Add testing instructions automatically on release PR

### PR DESCRIPTION
**Pull request by opr**
This PR adds more functionality to the release PR automation, specifically it extracts testing instructions from the PRs included in the release and adds them to `docs/testing/releases/{version}.md` as well as updating the index file to include a link to the new doc.

A rundown of what has changed:
- Exported ` fetchAllPullRequests` and `getEntry` from `utils/changelog` - this is necessary so we can extract changelog entries from PRs.
- Added a file in `utils` called `testing-instructions.js` - this exports a single function: `getTestingInstructions` which returns the testing instructions for this release as a string.
- Updated `lib/automations/release/branch-create-handler.js` to handle adding the instructions as part of the release PR creation.

### Testing instructions
To test this, you will need to:
- **Fork** the `woocommerce-gutenberg-products-block` and then unfork it (Go to this url: https://support.github.com/contact?tags=rr-forks and type `unfork` into the subject line. Follow the steps from the virtual assistant and wait 5-10 mins for the request to be actioned).
- Enable issues on your new unforked repository (go to `Settings > General > Features > Issues`)
- Activate GH actions
- Give read and write permissions to the workflows: Settings > Actions > General > Workflow permissions
- Allow GH actions to create PRs: Settings > Actions > General
- Create a milestone (I used 9.9.0, but pick whatever you like)
- Clone your repository locally.
- Create a PR on your repository, in this PR you should change the following file: https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/.github/workflows/release-pull-request.yml#L27
- Change the highlighted line to read: `uses: opr/automations@add/testing-instructions-automation` **note this is a different tag to the other PR so ensure this is correct!**
- Merge the PR
- Optionally create multiple PRs.
- Assign them all to the milestone you created earlier.
- Create a new branch, `release/9.9.0` or whatever milestone number you picked.
- Push this branch to the remote.
- Go to your repository on GitHub, you should see a new PR created for the release, and it should have added the testing instructions.

#### Additional testing
- [ ] Make a PR, mark it to be included in WooCommerce Core in the PR body - check it gets added to the correct section in the testing instructions.
- [ ] Make a PR, mark it to be included in Feature Plugin in the PR body - check it gets added to the correct section in the testing instructions.
- [ ] Mark a PR as `skip-changelog` - check it **does** get added to the correct section in the testing instructions.
- [ ] Make a PR, mark it as experimental in the PR body - check it **does not** get added to the testing instructions.

### Even more testing!
This tool even handles adding patch releases to the correct place in the `docs/testing/releases/README.md` file! It is pretty naive though and relies on that file being correctly indented, but with this fancy new tool, we won't have to worry about it!
- [ ] Make a release with an `x.x.1` patch version, verify the link to the testing instructions is placed in the correct place.
- [ ] Make a release with an `x.x.n` patch version (where `n` is greater than 1), verify the link to the testing instructions is placed in the correct place, you will need to ensure there's a previous patch with a minor version of 1 or more already though. I used `7.4.3`.

#### Failure modes 💥
This new automation relies on our PRs being formatted properly, if people don't include the correct markdown for the testing instructions, then the text will not be extracted properly or it will not be categorised properly.
- Do not add any testing instructions, do not tick any boxes, check that the testing instructions contain an error for that PR.
- Remove the `### User Facing Testing` header from your PR - check the testing instructions contain an error for that PR.

### CODE REVIEW

**Review by alexflorisca — APPROVED** [review]
Nice work @opr, this is super useful and will save us a lot of time! Well thought out edge cases as well 👍 I've given you all my feedback on Slack, so it's all good now from my side.

**Review by tarhi-saad — APPROVED** [review]
Thank you, @opr, for this great PR! I did go through all the tests and tried some edge cases. Almost every test was successful. There is only one small thing:

image

The patch release version `10.9.5` should be indented under the main release `10.9.0`. Besides this, it LGTM. 🚀

**Comment by opr** [comment]
Hey @tarhi-saad this is ready for another review! I would appreciate it if you could start from the top again as it's been a while. If you're using your own fork of blocks, be sure to update it to include the latest changes to our docs structure!

Changes included since last time I worked on this are:

- Change testing instructoins directory to `docs/internal-developers/testing`
- Create function to get the last patch release version in the correct order (`getLastPatchReleaseVersionLink`)

**Review by tarhi-saad — CHANGES_REQUESTED** [review]
Hello, @opr! 👋 I followed the testing steps from the start. For the most part, the PR is working well. There are only a few suggestions:

- If it's not a big effort, can we include the `Screenshots` section from the PRs in the testing instructions? Here is an example of [our current testing instructions](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/testing/releases/870.md). We added both the `User Facing Testing` and `Screenshots` sections.
- In this PR [we ensure that a testing category was assigned](https://github.com/woocommerce/automations/blob/928173f0619eb15041911a7a65176d551086aa3b/lib/utils/testing-instructions.js#L69) to include the testing instructions by checking [if a category was marked](https://github.com/woocommerce/automations/blob/928173f0619eb15041911a7a65176d551086aa3b/lib/utils/testing-instructions.js#L45) in the PR (e.g. `body.includes( '* [x] WooCommerce Core' )`). Can we support the checked categories with an uppercase `X` mark too (i.e., `body.includes( '* [X] WooCommerce Core`)?

I also tested a patch release, but I got the following error:

image

1. I followed the instruction [here](https://wooblocksrepo.wordpress.com/handling-releases/#release-branch) to create a patch release
2. I added [this PR](https://github.com/tarhi-saad/woocommerce-gutenberg-products-block/pull/58) to the corresponding milestone.
3. I pushed the patch release branch to the GitHub repo. Then the above error occurred.

I'm not sure if I did something wrong, but could you check if it's still works on your end?

**Pull request closed without merging**
